Nodejs sdk
Picovoice/cobra pull request #206
Opened 2024-01-25 23:28 UTC by albho

2024-01-30 20:04 UTC, ksyeo1010 commented on demo/nodejs/README.md
> +- Node.js 12+
16+

2024-01-30 20:04 UTC, ksyeo1010 commented on demo/nodejs/README.md
> +wish to detect voice activity.
```suggestion
Replace `${ACCESS_KEY}` with yours obtained from Picovoice Console and `${AUDIO_PATH}` with a path to an audio file you
wish to detect voice activity.
```

2024-01-30 20:05 UTC, laves commented on binding/nodejs/README.md
> +    - Raspberry Pi (2, 3, 4) NVIDIA Jetson Nano, and BeagleBone
@ksyeo1010 - I'm adding rpi5 to this PR

2024-01-31 19:04 UTC, albho commented on .github/workflows/nodejs-perf.yml
> +            init_performance_threshold_sec: 0.5
yeah it seems like windows tends to be around 0.2 and the others 0 or 0.001. Is this indicative of something wrong?

2024-01-31 19:10 UTC, albho commented on .github/workflows/nodejs-perf.yml
> +        run: yarn test perf.test.ts --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --num_test_iterations=50 --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} --proc_performan
both `num_test_iterations` and `proc_performance_threshold_sec` even if they're the same across tests?

2024-01-31 19:23 UTC, albho commented on binding/nodejs/src/cobra.ts
> +    }
Leopard does, but I can change it to do what Rhino & Porcupine do

2024-01-31 19:27 UTC, albho commented on binding/nodejs/src/index.ts
> +  getInt16Frames,
I think they can be useful - they're used in the demo and tests so users could benefit from having them too. Cheetah also exposes these as well

2024-02-02 18:28 UTC, ksyeo1010 commented on binding/nodejs/src/cobra.ts
> +      console.warn('Cobra is not initialized; nothing to destroy');
can you remove this console, we don't need to tell them.

2024-02-02 18:33 UTC, ksyeo1010 approved these changes

2024-02-02 19:43 UTC, laves requested changes

2024-02-02 19:43 UTC, laves commented on .github/workflows/nodejs-perf.yml
> +            init_performance_threshold_sec: 0.001
I'm not sure we should even keep the init test in - I don't think it adds any value. If we decide to add it, we can add it to all device based animals

2024-02-02 19:43 UTC, laves commented on README.md
> +handle.release();
I feel like we should only use `handle` as a variable name in C. Otherwise it's a bit too low-level for your average user.

2024-02-02 19:43 UTC, laves commented on binding/nodejs/README.md
> +an instance of Cobra.
It looks like you meant to add a code example here for the init, but combined it with the one below. Move the init up to here.

2024-02-02 19:43 UTC, laves commented on binding/nodejs/README.md
> +const handle = new Cobra(accessKey);
replace `handle` -> `cobra`

2024-02-02 19:43 UTC, laves commented on binding/nodejs/README.md
> +[Cobra Node.js demo package](../../demo/nodejs) provides command-line utilities for processing audio using cobra.
```suggestion
The [Cobra Node.js demo package](../../demo/nodejs) provides command-line utilities for processing audio using Cobra.
```

2024-02-02 19:43 UTC, laves commented on binding/nodejs/copy.js
> +mkdirp.sync('./lib/common');
cobra doesn't have a `.pv` file so no copies from lib common are needed

2024-02-02 19:43 UTC, laves commented on .github/workflows/nodejs-perf.yml
> +      - 'lib/common/**'
cobra doesn't have a `lib/common`

2024-02-02 19:43 UTC, laves commented on binding/nodejs/src/cobra.ts
> +   * @returns {number} Voice probability result.
Better to include the range when it's not obvious
```suggestion
   * @returns {number} Probability of voice activity. It is a floating-point number within [0, 1].
```

2024-02-02 19:43 UTC, laves commented on binding/nodejs/src/cobra.ts
> +    return VoiceProbabilityAndStatus!.is_voiced;
Weird capitalization here
```suggestion
    let voiceProbabilityAndStatus: VoiceProbabilityAndStatus | null = null;
    try {
      voiceProbabilityAndStatus = this._pvCobra.process(this._handle, pcm);
    } catch (err: any) {
      pvStatusToException(PvStatus[err.code as keyof typeof PvStatus], err);
    }

    const status = voiceProbabilityAndStatus!.status;
    if (status !== PvStatus.SUCCESS) {
      this.handlePvStatus(status, 'Cobra failed to process the audio frame');
    }

    return voiceProbabilityAndStatus!.is_voiced;
```

2024-02-02 19:43 UTC, laves commented on binding/nodejs/test/index.test.ts
> +];
It's not a good idea to get this detailed with the test expectations. Look at how the other tests do it:
e.g.) https://github.com/Picovoice/cobra/blob/main/binding/android/CobraTestApp/cobra-test-app/src/androidTest/java/ai/picovoice/cobra/testapp/CobraTest.java

They use a loss metric that gives a bit more breathing room for variation.

2024-02-02 19:43 UTC, laves commented on demo/nodejs/wave_util.js
> +//
don't we expose these utils already in the SDK?

2024-02-02 21:11 UTC, laves requested changes

2024-02-02 21:11 UTC, laves commented on binding/nodejs/copy.js
> -  console.log('../../lib/node copied.');
We still need the `lib/node` copy

2024-02-02 21:11 UTC, laves commented on demo/nodejs/mic.js
> +        )}${" ".repeat(emptyLength)}|`
Random request - can you also let `Ctrl+C` store recording? It just seems weird that I can only exit the demo with enter

2024-02-02 21:11 UTC, laves commented on demo/nodejs/mic.js
> +      const percentage = voiceProbability * 100;
when you try the demo without an access key it tells you 'no access key provided', but doesn't give you the usage instructions e.g. `-a, --access_key`

2024-02-02 23:17 UTC, laves approved these changes
Go ahead and release to NPM!

2024-02-05 23:49 UTC, merged